<?xml version="1.0" encoding="utf-8"?><Database Name="Photos" Class="PhotosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Photos.mdf;Integrated Security=True" SettingsObjectName="PhotoViewer.Properties.Settings" SettingsPropertyName="PhotosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PhotosTable" Member="PhotosTables">
    <Type Name="PhotosTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>