/* AUTHOR: DRAKE HETLAND
DATE: 10-10-2020
DESCRIPTION: PRACTICE USING SELECT QUERY
COULDN'T GET 16 AND 18 TO WORK */

USE COLONIAL_ADVENTURE_TOURS;

/* QUESTION 1 */
SELECT LAST_NAME FROM GUIDE WHERE STATE <> 'MA';

/* QUESTION 2 */
SELECT TRIP_NAME FROM TRIP WHERE TRIP_TYPE = 'BIKING';

/* QUESTION 3 */
SELECT TRIP_NAME FROM TRIP WHERE SEASON = 'SUMMER';

/* QUESTION 4 */
SELECT TRIP_NAME FROM TRIP WHERE TRIP_TYPE = 'HIKING' AND DISTANCE >10;

/* QUESTION 5 */
SELECT CUSTOMER_NUM, LAST_NAME, FIRST_NAME FROM CUSTOMER WHERE STATE IN ('NJ', 'NY', 'PA');

/* QUESTION 6 */
/* SELECT CUSTOMER_NUM, LAST_NAME, FIRST_NAME FROM CUSTOMER WHERE STATE IN ('NJ', 'NY', 'PA') ORDER BY STATE DESC;
SELECT CUSTOMER_NUM, LAST_NAME, FIRST_NAME FROM CUSTOMER WHERE STATE IN ('NJ', 'NY', 'PA') ORDER BY LAST_NAME; */

SELECT CUSTOMER_NUM, LAST_NAME, FIRST_NAME FROM CUSTOMER WHERE STATE IN ('NJ', 'NY', 'PA') ORDER BY STATE DESC, LAST_NAME;

/* QUESTION 7 */
/* SELECT TRIP_ID FROM TRIP WHERE STATE = 'ME' OR 'MA'; */
SELECT COUNT(*) FROM TRIP WHERE STATE IN ('ME', 'MA');

/* QUESTION 8 */
/* SELECT TRIP_ID, STATE FROM TRIP ORDER BY STATE; */
SELECT STATE, COUNT(TRIP_ID) FROM TRIP GROUP BY STATR ORDER BY STATE;

/* QUESTION 9 */
/* SELECT RESERVATION_ID FROM RESERVATION WHERE TRIP_PRICE BETWEEN 20 AND 75;
SELECT COUNT(TRIP_PRICE) FROM RESERVATION WHERE TRIP_PRICE BETWEEN 20.01 AND 74.99; */
SELECT COUNT(TRIP_PRICE) FROM RESERVATION WHERE TRIP_PRICE > 20 AND TRIP_PRICE < 75;

/* QUESTION 10 */
/* SELECT TRIP_ID, TRIP_TYPE FROM TRIP ORDER BY TRIP_TYPE; */
SELECT TRIP_TYPE, COUNT(TRIP_ID) FROM TRIP GROUP BY TRIP_TYPE ORDER BY TRIP_TYPE;

/* QUESTION 11 */
SELECT RESERVATION_ID, TRIP_ID, CUSTOMER_NUM, (TRIP_PRICE + OTHER_FEES) * NUM_PERSONS AS TOTAL_PRICE FROM RESERVATION WHERE NUM_PERSONS > 4;

/* QUESTION 12 */
SELECT TRIP_NAME FROM TRIP WHERE TRIP_NAME LIKE '%POND%';

/* QUESTION 13 */
SELECT LAST_NAME, FIRST_NAME FROM GUIDE WHERE HIRE_DATE < '2013-6-10';

/* QUESTION 14 */
/* SELECT AVG(DISTANCE), AVG(MAX_GRP_SIZE) FROM TRIP; */
SELECT TRIP_TYPE, AVG(DISTANCE), AVG(MAX _GRP_SIZE) FROM TRIP GROUP BY TRIP_TYPE ORDER BY TRIP_TYPE;

/* QUESTION 15 */
SELECT DISTINCT(SEASON) FROM TRIP;

/* QUESTION 16 */
/* SELECT RESERVATION_ID FROM RESERVATION WHERE (SELECT TRIP_NAME LIKE '%PADDLING%' FROM TRIP); */
SELECT RESERVATION_ID FROM RESERVATION WHERE TRIP_ID IN (SELECT TRIP_ID FROM TRIP WHERE TRIP_TYPE = 'PADDLING');

/* QUESTION 17 */
/* SELECT MAX(DISTANCE) FROM TRIP; */
SELECT MAX(DISTANCE) FROM TRIP WHERE TRIP_TYPE = 'BIKING';

/* QUESTION 18 */
/*SELECT COUNT(*) FROM RESERVATION GROUP BY TRIP_ID, SUM(TRIP_PRICE); */
SELECT TRIP_ID, SUM(TRIP_PRICE) FROM RESERVATION GROUP BY TRIP_ID HAVING COUNT(*) > 1 ORDER BY TRIP_ID; 

/* QUESTION 19 */
SELECT COUNT(RESERVATION_ID), SUM(NUM_PERSONS) FROM RESERVATION HAVING COUNT(RESERVATION_ID) <= 1;

/* QUESTION 20 */
SELECT RESERVATION_ID, TRIP_ID FROM RESERVATION WHERE TRIP_DATE <= '2016-7-1';
/* SELECT RESERVATION_ID, TRIP_ID FROM RESERVATION WHERE TRIP_DATE <= '2016-7-1' >= '2016-7-31'; */