USE COLONIAL_ADVENTURE_TOURS;

/* QUESTION 4 */
INSERT INTO PADDLING VALUES (43, 'LAKE CHAMPLAIN TOUR', 'VT', 16, 12, 'SUMMER');

/* EXAMPLE QUESTION 5 */
DELETE FROM NONGAME
WHERE CATEGORY = 'PZL';

/* EXAMPLE QUESTION 6 */
UPDATE LARGE_CONDO
SET BDRMS = NULL
WHERE LOCATION_NUM = 1
AND UNIT_NUM = 503;

/* QUESTION 7 */
ALTER TABLE PADDLING
ADD DIFFICULTY_LEVEL CHAR(3);

UPDATE PADDLING
SET DIFFICULTY_LEVEL = 'MOD';

/* QUESTION 10 */
ALTER TABLE PADDLING
MODIFY DIFFICULTY_LEVEL CHAR(3) NOT NULL;

