#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACS_Example_InClass_2022
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BruhnfoDatabase")]
	public partial class BrinkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBrable(Brable instance);
    partial void UpdateBrable(Brable instance);
    partial void DeleteBrable(Brable instance);
    #endregion
		
		public BrinkDataContext() : 
				base(global::ACS_Example_InClass_2022.Properties.Settings.Default.BruhnfoDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BrinkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrinkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrinkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrinkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Brable> Brables
		{
			get
			{
				return this.GetTable<Brable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Brable")]
	public partial class Brable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _Brunk;
		
		private string _Bruh;
		
		private string _Mutha;
		
		private string _Fatha;
		
		private bool _Suga;
		
		private int _Homebois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBrunkChanging(short value);
    partial void OnBrunkChanged();
    partial void OnBruhChanging(string value);
    partial void OnBruhChanged();
    partial void OnMuthaChanging(string value);
    partial void OnMuthaChanged();
    partial void OnFathaChanging(string value);
    partial void OnFathaChanged();
    partial void OnSugaChanging(bool value);
    partial void OnSugaChanged();
    partial void OnHomeboisChanging(int value);
    partial void OnHomeboisChanged();
    #endregion
		
		public Brable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brunk", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short Brunk
		{
			get
			{
				return this._Brunk;
			}
			set
			{
				if ((this._Brunk != value))
				{
					this.OnBrunkChanging(value);
					this.SendPropertyChanging();
					this._Brunk = value;
					this.SendPropertyChanged("Brunk");
					this.OnBrunkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bruh", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Bruh
		{
			get
			{
				return this._Bruh;
			}
			set
			{
				if ((this._Bruh != value))
				{
					this.OnBruhChanging(value);
					this.SendPropertyChanging();
					this._Bruh = value;
					this.SendPropertyChanged("Bruh");
					this.OnBruhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mutha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mutha
		{
			get
			{
				return this._Mutha;
			}
			set
			{
				if ((this._Mutha != value))
				{
					this.OnMuthaChanging(value);
					this.SendPropertyChanging();
					this._Mutha = value;
					this.SendPropertyChanged("Mutha");
					this.OnMuthaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fatha", DbType="VarChar(50)")]
		public string Fatha
		{
			get
			{
				return this._Fatha;
			}
			set
			{
				if ((this._Fatha != value))
				{
					this.OnFathaChanging(value);
					this.SendPropertyChanging();
					this._Fatha = value;
					this.SendPropertyChanged("Fatha");
					this.OnFathaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suga", DbType="Bit NOT NULL")]
		public bool Suga
		{
			get
			{
				return this._Suga;
			}
			set
			{
				if ((this._Suga != value))
				{
					this.OnSugaChanging(value);
					this.SendPropertyChanging();
					this._Suga = value;
					this.SendPropertyChanged("Suga");
					this.OnSugaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Homebois", DbType="Int NOT NULL")]
		public int Homebois
		{
			get
			{
				return this._Homebois;
			}
			set
			{
				if ((this._Homebois != value))
				{
					this.OnHomeboisChanging(value);
					this.SendPropertyChanging();
					this._Homebois = value;
					this.SendPropertyChanged("Homebois");
					this.OnHomeboisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
