USE TAL_DISTRIBUTORS;

DROP VIEW REPRESENTATIVE;

/*CREATE VIEW REPRESENTATIVE AS
SELECT LAST_NAME AS LAST, FIRST_NAME AS FIRST
FROM REP;*/

CREATE VIEW REPRESENTATIVE (LAST, FIRST) AS
SELECT LAST_NAME, FIRST_NAME
FROM REP;

SELECT * FROM REPRESENTATIVE WHERE LAST = 'TIAN';

CREATE USER 'guest'@'localhost' IDENTIFIED BY 'Password1';

SELECT USER FROM MYSQL.USER;

CREATE USER 'guest2' 
IDENTIFIED BY 'New_Password1';

SELECT USER FROM MYSQL.USER;

DROP USER 'guest'@'localhost';
/* OR USE DBMS MANAGEMENT GUI IN NAVIGATOR */ 