USE TAL_DISTRIBUTORS;

/* QUESTION 1 */
#A
CREATE VIEW MAJOR_CUSTOMER AS 
SELECT CUSTOMER_NUM, CUSTOMER_NAME, BALANCE, CREDIT_LIMIT, REP_NUM
FROM CUSTOMER
WHERE CREDIT_LIMIT <= 10000;

#B
SELECT CUSTOMER_NUM, CUSTOMER_NAME
FROM MAJOR_CUSTOMER
WHERE BALANCE > CREDIT_LIMIT;

#C
SELECT CUSTOMER_NUM, CUSTOMER_NAME
FROM MAJOR_CUSTOMER
WHERE BALANCE > CREDIT_LIMIT
AND CREDIT_LIMIT <= 10000;

/* QUESTION 6 */
#A
CREATE INDEX ITEM_INDEX1 ON ORDER_LINE(ITEM_NUM);

#B
CREATE INDEX ITEM_INDEX2 ON ITEM(CATEGORY DESC, STOREHOUSE);

/* QUESTION 9 */
ALTER TABLE ORDER_LINE
ADD FOREIGN KEY (ORDER_NUM) REFERENCES ORDERS(ORDER_NUM);