/* CHAPTER 4 EXTRA CREDIT ASSIGNMENT
AUTHOR: DRAKE HETLAND
DATE: 11-20-20
DESCRIPTION: EXTRA CREDIT ASSIGNMENT USING SOLMARIS REVIEW QUESTIONS INSTEAD OF COLONIAL ADVENTURE. */


USE SOLMARIS;

/* QUESTION 1 */
SELECT OWNER_NUM, LAST_NAME, FIRST_NAME
FROM OWNER;

/* QUESTION 2 */
SELECT * FROM LOCATION;

/* QUESTION 3 */
SELECT LAST_NAME, FIRST_NAME
FROM OWNER 
WHERE CITY = 'BOWTON';

/* QUESTION 4 */
SELECT LAST_NAME, FIRST_NAME
FROM OWNER 
WHERE CITY <> 'BOWTON';

/* QUESTION 5 */
SELECT LOCATION_NUM, UNIT_NUM
FROM CONDO_UNIT
WHERE SQR_FT <= 1200;

/* QUESTION 6 */
SELECT LOCATION_NUM, UNIT_NUM
FROM CONDO_UNIT
WHERE BDRMS = 3;

/* QUESTION 7 */
SELECT UNIT_NUM 
FROM CONDO_UNIT
WHERE BDRMS = 2
AND LOCATION_NUM = 2;

/* QUESTION 8 */
SELECT CONDO_ID
FROM CONDO_UNIT 
WHERE CONDO_FEE > 550
AND CONDO_FEE < 650;

/* QUESTION 9 */
SELECT UNIT_NUM
FROM CONDO_UNIT
WHERE LOCATION_NUM = 1
AND CONDO_FEE < 500;

/* QUESTION 10 */
SELECT CONDO_ID, CATEGORY_NUM, EST_HOURS, (EST_HOURS * 35) AS ESTIMATED_COST
FROM SERVICE_REQUEST;

/* QUESTION 11 */
SELECT OWNER_NUM, LAST_NAME
FROM OWNER
WHERE STATE = 'FL'
OR STATE = 'GA' 
OR STATE = 'SC';

/* QUESTION 12 */
SELECT LOCATION_NUM, UNIT_NUM, SQR_FT, CONDO_FEE
FROM CONDO_UNIT
ORDER BY SQR_FT, CONDO_FEE;

/* QUESTION 13 */
SELECT COUNT(*)
FROM CONDO_UNIT
WHERE BDRMS = 1
AND LOCATION_NUM = 1;

SELECT COUNT(*)
FROM CONDO_UNIT
WHERE BDRMS = 1
AND LOCATION_NUM = 2;

/* QUESTION 14 */
SELECT SUM(CONDO_FEE)
FROM CONDO_UNIT;

/* QUESTION 15 */
SELECT OWNER_NUM, LAST_NAME
FROM OWNER
WHERE STATE LIKE ('FL')
OR STATE LIKE ('GA')
OR STATE LIKE ('SC');

/* QUESTION 16 */
SELECT * FROM SERVICE_REQUEST
WHERE DESCRIPTION LIKE '%PANTRY%';