/* QUESTION 6 */
CREATE OR REPLACE PROCEDURE DISP_ITEM_CATEGORY (I_CATEGORY IN ITEM.CATEGORY%TYPE) AS 
I_NUM ITEM.ITEM_NUM%TYPE;
I_DESC ITEM.DESCRIPTION%TYPE;
I_SH ITEM.STORHOUSE%TYPE;
I_PRICE ITEM.PRICE%TYPE;

CURSOR ITEMGROUP IS
SELECT ITEM_NUM, DESCRIPTION, STOREHOUSE, PRICE
FROM ITEM
WHERE CATEGORY = I_CATEGORY

BEGIN
	OPEN ITEMGROUP
    
    LOOP
		FETCH ITEMGROUP INTO I_NUM, I_DESC, I_SH, I_PRICE;
        EXIT WHEN ITEMGROUP%NOTFOUND;