/* CHAPTER 6 EXTRA CREDIT ASSIGNMENT
AUTHOR: DRAKE HETLAND
DATE: 11-20-20
DESCRIPTION: EXTRA CREDIT ASSIGNMENT USING SOLMARIS REVIEW QUESTIONS INSTEAD OF COLONIAL ADVENTURE. */

DROP TABLE IF EXISTS LARGE_CONDO;
USE SOLMARIS;

/* QUESTION 1 */
CREATE TABLE LARGE_CONDO
(LOCATION_NUM DECIMAL(2,0),
UNIT_NUM CHAR(3),
BDRMS DECIMAL (2,0),
BATHS DECIMAL (2,0),
CONDO_FEE DECIMAL(6,2),
OWNER_NUM CHAR(5),
PRIMARY KEY(LOCATION_NUM, UNIT_NUM));

/* QUESTION 2 */
INSERT INTO LARGE_CONDO
SELECT LOCATION_NUM, UNIT_NUM, BDRMS, BATHS, CONDO_FEE, OWNER_NUM
FROM CONDO_UNIT
WHERE SQR_FT > 1500;

/* QUESTION 3 */
UPDATE LARGE_CONDO
SET CONDO_FEE = CONDO_FEE + 150;

/* QUESTION 4 */
UPDATE LARGE_CONDO
SET CONDO_FEE = CONDO_FEE * .99
WHERE CONDO_FEE > 750;

/* QUESTION 5 */
INSERT INTO LARGE_CONDO
VALUES (1, '605', 3, 3, 775, 'FE182');

/* QUESTION 6 */
DELETE FROM LARGE_CONDO
WHERE OWNER_NUM = 'AN175';

/* QUESTION 7 */
UPDATE LARGE_CONDO
SET BDRMS = NULL
WHERE LOCATION_NUM = 1
AND UNIT_NUM = '503';

/* QUESTION 8 */
ALTER TABLE LARGE_CONDO
ADD OCCUPIED CHAR(1);

UPDATE LARGE_CONDO
SET OCCUPIED = 'Y';

/* QUESTION 9 */
UPDATE LARGE_CONDO
SET OCCUPIED = 'N'
WHERE UNIT_NUM = 'C06';

/* QUESTION 10 */
ALTER TABLE LARGE_CONDO
MODIFY CONDO_FEE DECIMAL(6,2) NOT NULL;

/* QUESTION 11 */
/* DROP TABLE LAEGE_CONDO; */

/* QUESTION 12 */
/* CREATE TABLE LARGE_CONDO
(LOCATION_NUM SMALLINT(2),
UNIT_NUM CHAR(3),
BDRMS SMALLINT (2),
BATHS SMALLINT (2),
CONDO_FEE DECIMAL(6,2),
OWNER_NUM CHAR(5),
PRIMARY KEY(LOCATION_NUM, UNIT_NUM)); */
