/* CHAPTER 5 EXTRA CREDIT ASSIGNMENT
AUTHOR: DRAKE HETLAND
DATE: 11-20-20
DESCRIPTION: EXTRA CREDIT ASSIGNMENT USING COLONIAL ADVENTURE REVIEW QUESTIONS INSTEAD OF SOLMARIS */

USE COLONIAL_ADVENTURE_TOURS;

/* QUESTION 1 */
SELECT RESERVATION_ID, TRIP_ID, C.CUSTOMER_NUM, LAST_NAME
FROM RESERVATION R, CUSTOMER C
WHERE R.CUSTOMER_NUM = C.CUSTOMER_NUM
ORDER BY LAST_NAME;

/* QUESTION 2 */
SELECT RESERVATION_ID, TRIP_ID, NUM_PERSONS
FROM RESERVATION R, CUSTOMER C
WHERE R.CUSTOMER_NUM = C.CUSTOMER_NUM
AND FIRST_NAME IN (SELECT FIRST_NAME FROM CUSTOMER WHERE FIRST_NAME = 'RYAN');

/* QUESTION 3 */
SELECT TRIP_NAME
FROM TRIP T, TRIP_GUIDES G
WHERE T.TRIP_ID = G.TRIP_ID
AND GUIDE_NUM = 'AM01';

/* QUESTION 4 */
SELECT TRIP_NAME
FROM TRIP T, TRIP_GUIDES G
WHERE T.TRIP_ID = G.TRIP_ID
AND GUIDE_NUM = 'BR01'
AND TYPE = 'BIKING';

/* QUESTION 5 */
SELECT LAST_NAME, TRIP_NAME, START_LOCATION
FROM CUSTOMER C, RESERVATION R
WHERE R.CUSTOMER_NUM = C.CUSTOMER_NUM
AND TRIP_DATE = '2016-7-23';

/* QUESTION 6 */


/* QUESTION 7 */


/* QUESTION 8 */


/* QUESTION 9 */


/* QUESTION 10 */


/* QUESTION 11 */


/* QUESTION 12 */


/* QUESTION 13 */


/* QUESTION 14 */


/* QUESTION 15 */


/* QUESTION 16 */


/* QUESTION 17 */


/* QUESTION 18 */
