/* AUTHOR: DRAKE HETLAND
DATE: 11-11-2020
DESCRIPTION: EXAM GOING OVER CONCEPTS LEARNED IN CHAPTERS 5 AND 6 */

USE WORLD;
DROP TABLE IF EXISTS EUROPE;

/* QUESTION 1 */
SELECT ID, CITY_NAME
FROM CITY
WHERE COUNTRY_CODE IN 
(SELECT COUNTRY_CODE FROM COUNTRY WHERE GNP > 7500000);

/* QUESTION 2 */
SELECT ID, CITY_NAME
FROM CITY
WHERE EXISTS 
(SELECT COUNTRY_CODE 
FROM COUNTRY 
WHERE CITY.COUNTRY_CODE = COUNTRY.COUNTRY_CODE
AND GNP > 7500000);

/* QUESTION 3 */
SELECT I.ID, C.ID
FROM CITY I, CITY C
WHERE I.POPULATION = C.POPULATION
AND I.ID < C.ID ORDER BY I.ID, C.ID;

/* QUESTION 4 */
/*SELECT C.COUNTRY_CODE, LANGUAGE_NAME
FROM COUNTRY C, COUNTRY_LANGUAGE L
WHERE C.COUNTRY_CODE = L.COUNTRY_CODE
AND IS_OFFICIAL = 'T'
AND PERCENTAGE >= 90
UNION
SELECT COUNTRY_CODE, LANGUAGE_NAME
FROM COUNTRY_LANGUAGE
WHERE C.COUNTRY_CODE = L.COUNTRY_CODE; */

SELECT N.COUNTRY_CODE, COUNTRY_NAME, LANGUAGE_NAME
FROM COUNTRY N, COUNTRY_LANGAUGE L
WHERE N.COUNTRY_CODE = L.COUNTRY_CODE
AND L.PERCENTAGE >= 90
UNION
SELECT N.COUNTRY_CODE, COUNTRY_NAME, LANGAUGE_NAME
FROM COUNTRY N, COUNTRY_LANGAUGE L
WHERE N.COUNTRY_CODE = L.COUNTRY_CODE
AND IS_OFFICIAL = 'T';

/* QUESTION 5 */
/*SELECT COUNTRY.COUNTRY_CODE, COUNTRY_NAME, LANGUAGE_NAME
FROM COUNTRY, COUNTRY_LANGUAGE
WHERE COUNTRY.COUNTRY_CODE = COUNTRY_LANGUAGE.COUNTRY_CODE
AND IS_OFFICIAL = 'T'
AND PERCENTAGE >= 90;*/

SELECT N.COUNTRY_CODE, COUNTRY_NAME, LANGUAGE_NAME
FROM COUNTRY N, COUNTRY_LANGAUGE L
WHERE N.COUNTRY_CODE = L.COUNTRY_CODE
AND L.PERCENTAGE >= 90
AND LANGUAGE_NAME IN
(SELECT LANGAUGE_NAME
FROM COUNTRY_LANGAUGE 
WHERE IS_OFFICIAL = 'T');

/* QUESTION 6 */
/*SELECT COUNTRY.COUNTRY_CODE, COUNTRY_NAME, LANGUAGE_NAME
FROM COUNTRY, COUNTRY_LANGUAGE
WHERE COUNTRY.COUNTRY_CODE = COUNTRY_LANGUAGE.COUNTRY_CODE
AND IS_OFFICIAL = 'F'
AND PERCENTAGE >= 90;*/

SELECT N.COUNTRY_CODE, COUNTRY_NAME, LANGUAGE_NAME
FROM COUNTRY N, COUNTRY_LANGAUGE L
WHERE N.COUNTRY_CODE = L.COUNTRY_CODE
AND L.PERCENTAGE >= 90
AND LANGUAGE_NAME NOT IN
(SELECT LANGAUGE_NAME
FROM COUNTRY_LANGAUGE 
WHERE IS_OFFICIAL = 'T');

/* QUESTION 7 */
SELECT COUNTRY_CODE, COUNTRY_CODE_2
FROM COUNTRY
WHERE GNP < 500000
AND POPULATION > ANY(SELECT POPULATION
FROM COUNTRY
WHERE GNP > 1000000);

/* QUESTION 8 */
SELECT COUNTRY_CODE, COUNTRY_CODE_2
FROM COUNTRY
WHERE GNP < 500000
AND POPULATION > ALL(SELECT POPULATION
FROM COUNTRY
WHERE GNP > 1000000);

/* QUESTION 9 */
CREATE TABLE EUROPE
(COUNTRY_CODE CHAR (3) PRIMARY KEY,
COUNTRY_NAME CHAR (52),
POPULATION INT (11),
GNP DECIMAL (10,0),
GOVT_FORM CHAR (45));

/* QUESTION 10 */
INSERT INTO EUROPE
SELECT COUNTRY_CODE, COUNTRY_NAME, POPULATION, GNP, GOVERNMENT_FORM
FROM COUNTRY
WHERE CONTINENT = 'EUROPE';

/* QUESTION 11 */
INSERT INTO EUROPE
VALUES ('AVA', 'Avalon', 500000, 750000, 'Monarchy');

/* QUESTION 12 */
DELETE FROM EUROPE
WHERE COUNTRY_CODE = 'BEL';

/* QUESTION 13 */
UPDATE EUROPE
SET GNP = NULL
WHERE COUNTRY_NAME = 'ALBANIA';

/* QUESTION 14 */
ALTER TABLE EUROPE
MODIFY COUNTRY_NAME CHAR (45) NOT NULL;

/* QUESTION 15 */
ALTER TABLE EUROPE
ADD COLUMN AT_PEACE BOOLEAN;

UPDATE EUROPE
SET AT_PEACE = TRUE;

/* EXTRA CREDIT */
/*DROP TABLE EUROPE;