/* QUESTION 1 */
SELECT COUNTRY_CODE, COUNTRY_NAME, CONTINENT FROM COUNTRY;

/* QUESTION 2 */ 
SELECT * FROM COUNTRY_LANGUAGE;

/* QUESTION 3 */
SELECT * FROM CITY ORDER BY COUNTRY_CODE, DISTRICT;

/* QUESTION 4 */
SELECT COUNTRY_NAME FROM COUNTRY WHERE POPULATION >= 100000000;

/* QUESTION 5 */
SELECT COUNTRY_CODE FROM COUNTRY_LANGUAGE WHERE IS_OFFICIAL = 'F' AND PERCENTAGE > 90;

/* QUESTION 6 */
SELECT CITY_NAME, COUNTRY_CODE FROM CITY WHERE COUNTRY_CODE LIKE '%USA%';
/* SELECT CITY_NAME, COUNTRY_CODE FROM CITY WHERE COUNTRY_CODE = 'USA'; */

/* QUESTION 7 */
SELECT COUNTRY_NAME, REGION FROM COUNTRY WHERE CONTINENT != 'ASIA';
/* SELECT COUNTRY_NAME, REGION FROM COUNTRY WHERE CONTINENT <> 'ASIA'; /*

/* QUESTION 8 */
SELECT COUNTRY_CODE, COUNTRY_NAME, GNP FROM COUNTRY WHERE GNP BETWEEN 500000 AND 1000000;
/* SELECT COUNTRY_CODE, COUNTRY_NAME, GNP FROM COUNTRY WHERE GNP >= 500000 <= 1000000; */

/* QUESTION 9 */
SELECT COUNTRY_NAME, SURFACE_AREA, POPULATION, (POPULATION / SURFACE_AREA) AS POPULATON_DENSITY FROM COUNTRY WHERE CONTINENT = 'EUROPE';

/* QUESTION 10 */
SELECT COUNTRY_CODE FROM COUNTRY_LANGUAGE WHERE LANGUAGE_NAME LIKE 'J%';

/* QUESTION 11 */
SELECT COUNTRY_CODE FROM COUNTRY WHERE GNP < GNP_OLD;

/* QUESTION 12 */
SELECT CITY_NAME, COUNTRY_CODE, DISTRICT FROM CITY WHERE MAX(POPULATION);/*AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA*/

/* QUESTION 13 */
SELECT COUNTRY_CODE FROM COUNTRY WHERE CAPITAL IS NULL;

/* QUESTION 14 */
SELECT COUNTRY_CODE, SUM(POPULATION) AS NATIONAL_POPULATION FROM CITY GROUP BY COUNTRY_CODE ORDER BY COUNTRY_CODE;

/* QUESTION 15 */
SELECT COUNTRY_CODE, LANGUAGE_NAME FROM COUNTRY_LANGUAGE WHERE LANGUAGE_NAME LIKE '%IAN%' AND PERCENTAGE BETWEEN 50 AND 75;