USE WORLD;
DROP VIEW IF EXISTS LARGE_COUNTRY;

/* QUESTION 1 */
CREATE VIEW LARGE_COUNTRY AS 
SELECT COUNTRY_CODE, COUNTRY_NAME, CONTINENT
FROM COUNTRY WHERE SURFACE_AREA > 3000000;

SELECT COUNTRY_CODE, COUNTRY_NAME, CONTINENT
FROM LARGE_COUNTRY
WHERE CONTINENT = ASIA;

SELECT COUNTRY_CODE, COUNTRY_NAME, CONTINENT
FROM LARGE_COUNTRY
WHERE CONTINENT = ASIA
AND SURFACE_AREA > 3000000;

/* QUESTION 2 */
CREATE VIEW EUROPEAN_CITIES AS
SELECT CITY_NAME, Y.COUNTRY_NAME, Y.POPULATION, COUNTRY_CODE
FROM CITY Y, COUNTRY C
WHERE Y.COUNTRY_CODE = C.COUNTRY_CODE
AND CONTINENT = 'EUROPE';

SELECT CITY_NAME, COUNTRY_NAME, POPULATION, COUNTRY_CODE
FROM EUROPEAN_CITIES
WHERE POPULATION > 1500000;

SELECT CITY_NAME, Y.COUNTRY_NAME, Y.POPULATION, COUNTRY_CODE
FROM CITY Y, COUNTRY C
WHERE Y.COUNTRY_CODE = C.COUNTRY_CODE
AND CONTINENT = 'EUROPE'
AND POPULATION > 1500000;

/* QUESTION 3 */
/*1*/
GRANT SELECT ON CITY TO BARTON;

/*2*/
GRANT INSERT ON COUNTRY_LANGUAGE TO KENT, ROGERS;
GRANT INSERT ON CITY TO KENT, ROGERS;

/*3*/
GRANT UPDATE ON CITY TO BANNER, PARKER;

/*4*/
GRANT SELECT ON COUNTRY TO BARTON, KENT, ROGERS, BANNER, PARKER, WAYNE;

/*5*/
GRANT DELETE ON COUNTRY TO WAYNE;
GRANT INSERT ON COUNTRY TO WAYNE;

/*6*/
GRANT INDEX ON CITY TO BANNER;

/*7*/
GRANT ALTER ON COUNTRY_LANGUAGE TO BANNER, WAYNE;

/*8*/
GRANT ALL ON CITY TO WAYNE;
GRANT ALL ON COUNTRY TO WAYNE;

/* QUESTION 4 */
REVOKE UPDATE FROM BANNER;
REVOKE SELECT FROM BANNER;
REVOKE INDEX FROM BANNER;

/* QUESTION 5 */
CREATE INDEX COUNTRY_INDEX ON COUNTRY(COUNTRY_NAME, CONTINENT);

/* QUESTION 6 */
ALTER TABLE CITY
ADD FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY;

/* QUESTION 7 */
ALTER TABLE COUNTRY_LANGUAGE
ADD CHECK (IS_OFFICIAL IN ('T', 'F'));

/* QUESTION 8 */


/* QUESTION 9 */

